config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  unauthenticated :user do
    devise_scope :user do
      root to: 'unauthenticated#index', as: :unauthenticated_root
    end
  end

  authenticated :user do
    root to: 'posts#index', as: :authenticated_root
  end

  resources :posts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  has_rich_text :content
  belongs_to :user

  validates :title, :content, presence: true

  scope :last_created, -> { order(created_at: :desc)}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar
  has_many :posts, dependent: :destroy

  validates :username, presence: true, uniqueness: true

  def full_name
    return "#{first_name} #{last_name}" if first_name && last_name
    'Bruce Wayne'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :first_name, :last_name, :avatar])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  def index
    @posts = Post.includes(:user).last_created
  end

  # GET /posts/:id
  def show
  end

  # GET /posts/new
  def new
    @post = current_user.posts.new
  end

  # GET /posts/:id/edit
  def edit
  end

  # POST /posts
  def create
    @post = current_user.posts.new(post_params)

    if @post.save
      redirect_to authenticated_root_path, notice: 'Question was successfully created.'
    else
      render partial: 'shared/error_messages', locals: {resource: @post}, status: :bad_request
    end
  end

  # PATCH/PUT /posts/:id
  def update
    if @post.update(post_params)
      redirect_to authenticated_root_path, notice: 'Question was successfully updated.'
    else
      render partial: 'shared/error_messages', locals: {resource: @post}, status: :bad_request
    end
  end

  # DELETE /posts/:id
  def destroy
    @post.destroy
    redirect_to authenticated_root_path, notice: 'Question was successfully destroyed.'
  end

  private

    def post_params
      params.require(:post).permit(:title, :content)
    end

    def set_post
      @post = Post.friendly.find(params[:id])
    end
end

app/controllers/unauthenticated_controller.rb
class UnauthenticatedController < ApplicationController
  layout 'unauthenticated'

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    {
      success: "alert-success",
      error: "alert-danger",
      alert: "alert-warning",
      notice: "alert-info"
    }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end

  def get_user_avatar(user:, size:)
    if user.avatar.attached?
      image_tag(user.avatar, height: size, width: size, class: "rounded")
    else
      image_tag(gravatar_image_url(user.email, size: size * 2), height: size, width: size, class: "rounded")
    end
  end
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Community</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flash_messages' %>

    <div class="container py-3">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/unauthenticated.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Community</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flash_messages' %>

    <div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<div data-controller="question-form">
  <%= form_with(model: post,
      html: { data: { type: 'html',
                      target: 'question-form.form',
                      action: "ajax:send->question-form#disableSubmitButton ajax:error->question-form#onPostError" } }) do |form| %>

    <div class="comment-errors" data-target="question-form.commentErrors">
    </div>

    <div class="form-group">
      <%= form.label :title %>
      <%= form.text_field :title, class: 'form-control', data: { target: 'question-form.titleInput' } %>
    </div>

    <div class="form-group">
      <%= form.label :content %>
      <%= form.rich_text_area :content %>
    </div>

    <div class="form-group">
      <%= form.button 'Create question', class: 'btn btn-primary', data: { target: 'question-form.submitButton' } %>
    </div>
  <% end %>
</div>

app/views/posts/edit.html.haml
.container
  .text-center
    = link_to 'Back', :back, class: 'float-right'
    %h1 Edit your question
  .row
    .col-lg-8.ml-auto.mr-auto
      = render 'form', post: @post

app/views/posts/index.html.haml
.container
  .row
    .col-lg-8
      - @posts.each do |post|
        .card.shadow.mb-3
          .card-body
            - if current_user.id == post.user_id
              %p= link_to 'Edit', edit_post_path(post), class: 'float-right'
            %h5.card-title
              = link_to post.title, post_path(post)
            .user.d-flex
              .mr-2
                = get_user_avatar(user: post.user, size: 40)
              .info.d-flex
                %span.item.font-weight-bold
                  = post.user.username.capitalize
                %span.item.font-weight-light.text-muted
                  = post.user.full_name
              .created-at
                %span.font-weight-light.text-muted
                  = time_ago_in_words(post.created_at) 
                  ago
          .card-footer.text-right
            %a.card-link{:href => "#"}
              %i.far.fa-comments
    .col-lg-4
      .card
        .card-header Tags
        .card-body
          %h5.card-titlePrimary card title
          %p.card-text Some quick example text to build on the card title and make up the bulk of the card's content.</p>

app/views/posts/new.html.haml
.container
  .text-center
    = link_to 'Back', :back, class: 'float-right'
    %h1 Ask something
  .row
    .col-lg-8.ml-auto.mr-auto
      = render 'form', post: @post

app/views/shared/_error_messages.html.erb
<div id="error_explanation">
  <ul>
    <% resource.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</div>

app/views/shared/_flash_messages.html.erb
<% flash.each do |msg_type, message| %>
  <div class="alert <%= bootstrap_class_for(msg_type) %>">
    <div class="container">
      <button class="close" data-dismiss="alert"><span>×</span></button>
      <%= message %>
    </div>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-light">
  <div class="container">
  <%= link_to 'Community', user_signed_in? ? authenticated_root_path : unauthenticated_root_path, class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarMain" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarMain">
      <ul class="navbar-nav mr-auto mt-2 mt-md-0">
        <li class="nav-item">
          <%= link_to 'Ask something', new_post_path %>
        </li>
      </ul>

      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <%= link_to "#", id: "navbar-dropdown", class: "nav-link dropdown-toggle", data: { target: "nav-account-dropdown", toggle: "dropdown" }, aria: { haspopup: true, expanded: false } do %>
              <%= get_user_avatar(user: current_user, size: 30) %>
            <% end %>
            <div id="nav-account-dropdown" class="dropdown-menu dropdown-menu-right" aria-labelledby="navbar-dropdown">
              <%= link_to "Settings", edit_user_registration_path, class: "dropdown-item" %>
              <div class="dropdown-divider"></div>
              <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item"><%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "Login", new_user_session_path, class: "nav-link" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/unauthenticated/index.html.erb
<main class="hero">
  <div class="container h-100">
    <div class="row h-100 align-items-center">
      <div class="col-12 hero-content text-center">
        <h1 class="display-4">We are a developers community</h1>
        <h3 class="font-weight-light">We love helping others</h3>
      </div>
    </div>
  </div>
  <div class="transparency"></div>
</main>